# Generated by Django 6.0 on 2025-12-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='身長(cm)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='introduction',
            field=models.TextField(blank=True, max_length=500, verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
