# Generated by Django 6.0 on 2025-12-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hide_profile_image',
            field=models.BooleanField(default=False, verbose_name='プロフィール画像を非公開にする'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_anonymous_account',
            field=models.BooleanField(default=False, verbose_name='匿名アカウントにする（名前を伏せる）'),
        ),
    ]
