# Generated by Django 6.0 on 2026-01-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_hide_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exp',
            field=models.PositiveIntegerField(default=0, verbose_name='経験値'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_bonus_date',
            field=models.DateField(blank=True, null=True, verbose_name='最終ログインボーナス日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='レベル'),
        ),
    ]
