# Generated by Django 6.0 on 2026-01-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_exp_customuser_last_login_bonus_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_like_bonus_date',
            field=models.DateField(blank=True, null=True, verbose_name='最終いいねボーナス日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_total_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='前回確認時の合計いいね数'),
        ),
    ]
