# Generated by Django 6.0 on 2025-12-12 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='ミッション名')),
                ('description', models.TextField(verbose_name='詳細説明')),
                ('difficulty', models.IntegerField(default=1, verbose_name='難易度')),
            ],
        ),
        migrations.CreateModel(
            name='MissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='達成日時')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='達成コメント')),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='missions.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
