# Generated by Django 6.0 on 2025-12-12 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='タグ名')),
                ('icon', models.CharField(blank=True, max_length=10, null=True, verbose_name='アイコン')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='記録日')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='体重(kg)')),
                ('body_fat', models.FloatField(blank=True, null=True, verbose_name='体脂肪率(%)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/', verbose_name='自撮り写真')),
                ('note', models.TextField(blank=True, null=True, verbose_name='一言メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conditions', models.ManyToManyField(blank=True, to='records.conditiontag', verbose_name='コンディション')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
