# Generated by Django 6.0 on 2025-12-16 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meals/%Y/%m/')),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='records.dailyrecord')),
            ],
        ),
    ]
