# Generated by Django 6.0 on 2025-12-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', '☀️ 朝食'), ('lunch', '🍽️ 昼食'), ('dinner', '🌙 夕食'), ('snack', '🍪 間食')], default='snack', max_length=20),
        ),
    ]
