# Generated by Django 6.0 on 2025-12-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='匿名で投稿する'),
        ),
        migrations.AddField(
            model_name='post',
            name='show_profile_image',
            field=models.BooleanField(default=True, verbose_name='プロフィール画像を表示する'),
        ),
    ]
