# Generated by Django 6.0 on 2025-12-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_post_is_anonymous_post_show_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='show_profile_image',
        ),
        migrations.AddField(
            model_name='post',
            name='hide_profile_image',
            field=models.BooleanField(default=False, verbose_name='プロフィール画像を隠す'),
        ),
    ]
