# Generated by Django 6.0 on 2025-12-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hide_profile_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_anonymous',
        ),
    ]
